//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Belle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Belle.Resources.JsResources", typeof(JsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to require.config(&quot;##RequireJsConfig##&quot;);
        ///
        ///require(&quot;##RequireJsInitialize##&quot;, function (angular, app) {
        ///  //This function will be called when all the dependencies
        ///  //listed above are loaded. Note that this function could
        ///  //be called before the page is loaded.
        ///  //This callback is optional.
        ///
        ///  jQuery(document).ready(function () {
        ///    angular.bootstrap(document, [&apos;umbraco&apos;]);
        ///  });
        ///});
        ///.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    waitSeconds: 120,
        ///    paths: {
        ///        jquery: &apos;../lib/jquery/jquery-1.8.2.min&apos;,
        ///        jqueryCookie: &apos;../lib/jquery/jquery.cookie&apos;,
        ///        bootstrap: &apos;../lib/bootstrap/js/bootstrap&apos;,
        ///        underscore: &apos;../lib/underscore/underscore&apos;,
        ///        angular: &apos;../lib/angular/angular.min&apos;,
        ///        angularResource: &apos;../lib/angular/angular-resource&apos;,
        ///        statemanager: &apos;../lib/angular/statemanager&apos;,
        ///        text: &apos;../lib/require/text&apos;,
        ///        async: &apos;../lib/require/async&apos;
        ///    },
        ///    shim: {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequireJsConfig {
            get {
                return ResourceManager.GetString("RequireJsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    &apos;angular&apos;,
        ///    &apos;app&apos;,
        ///    &apos;jquery&apos;,
        ///    &apos;jqueryCookie&apos;,
        ///    &apos;statemanager&apos;,
        ///    &apos;bootstrap&apos;,
        ///    &apos;services/services&apos;,
        ///    &apos;controllers/controllers.application&apos;,
        ///    &apos;controllers/controllers.editors&apos;,
        ///    &apos;controllers/controllers.propertyeditor&apos;,
        ///    &apos;filters/filters&apos;,
        ///    &apos;directives/directives&apos;,
        ///    &apos;routes&apos;
        ///].
        /// </summary>
        internal static string RequireJsInitialize {
            get {
                return ResourceManager.GetString("RequireJsInitialize", resourceCulture);
            }
        }
    }
}
